accounts/urls.py
from django.urls import path
from .views import UserRegistationsForms,UserBankAccountUpdate,UserLoginView,user_logout,PasswordChangeView

urlpatterns = [
   
    path('register/', UserRegistationsForms.as_view(),name='register'),
    path('profile/', UserBankAccountUpdate.as_view(),name='profile'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('logout/', user_logout, name='logout'),
]

bank_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(),name='home'),
    path('account/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from .views import DepositMoneyView,WithdrawMoneyView,TransactionReportView,LoanRequestView,PayLoanView,LoanListView,TransferMoneyView

urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionReportView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("loan_request/", LoanRequestView.as_view(), name="loan_request"),
    path("loans/", LoanListView.as_view(), name="loan_list"),
    path("transfer-money/", TransferMoneyView.as_view(), name="transfer_money"),
    path("loans/<int:loan_id>/", PayLoanView.as_view(), name="pay"),
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE
# Create your models here.

class Transactions(models.Model):
    account = models.ForeignKey(UserBankAccount, related_name='transactions' ,on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2,max_digits=12)
    account_no = models.IntegerField(blank=True,default=0)
    balance_after_transactions = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null = True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False)
    
    class Meta:
        ordering =['timestamp']
        

transactions/forms.py
from django import forms
from .models import Transactions
from accounts.models import UserBankAccount

class TransactionsForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ['amount' ,'account_no', 'transaction_type']
        
    def __init__(self,*args,**kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args,**kwargs)
        self.fields['transaction_type'].disabled =True
        self.fields['transaction_type'].widget =forms.HiddenInput()
        
    def save(self, commit = True):
        self.instance.account =self.account
        self.instance.balance_after_transaction =self.account.balance
        return super().save()
    
class DepositForm(TransactionsForm):
    def clean_amount(self):
        min_deposit_amount=100
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f"You need to deposit at least {min_deposit_amount}"
                
            )
        return amount
class WithdrawalFrom(TransactionsForm):
    def clean_amount(self):
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance
        
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )
        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )
        
        if amount > balance:
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )
        return amount
class LoabRequestForm(TransactionsForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        
        return amount

class TransferMoney(TransactionsForm):
    def clean(self):
        cleaned_data = super().clean()
        account = self.account
        amount = cleaned_data.get('amount')
        account_no = cleaned_data.get('account_no')

        if amount and amount > account.balance:
            raise forms.ValidationError("You don't have enough balance.")

        if account_no == account.account_no:
            raise forms.ValidationError("You cannot transfer to your own account.")

        try:
            target_account = UserBankAccount.objects.get(account_no=account_no)
        except UserBankAccount.DoesNotExist:
            raise forms.ValidationError("Target account not found.")

        cleaned_data['to_account'] = target_account
        return cleaned_data
        
        
        
        
    

transactions/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import get_object_or_404,redirect
from django.views import View
from django.views.generic import CreateView,ListView
from transactions.constants import DEPOSIT,WITHDRAWAL,LOAN,LOAN_PAID,TRANSFER_MONEY
from datetime import datetime
from django.db.models import Sum
from django.core.mail import EmailMessage,EmailMultiAlternatives
from django.template.loader import render_to_string
from transactions.forms import DepositForm,WithdrawalFrom,LoabRequestForm,TransferMoney
from .models import Transactions
from django.http import HttpResponse
from accounts.models import UserBankAccount
# Create your views here.

def transaction_email_send(user,amount,subject,template):
    message = render_to_string(template,{
        'user':user,
        'amount':amount
    })
    send_email = EmailMultiAlternatives(subject,'',to=[user.email])
    send_email.attach_alternative(message,"text/html")
    send_email.send()

class TransactionCreateMixin(LoginRequiredMixin,CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transactions
    title = ''
    success_url = reverse_lazy('transaction_report')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
             'title': self.title
        })
        return context
    
class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit'
    
    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        
        account.balance += amount
        account.save(
            update_fields=['balance']
        )
        transaction_email_send(self.request.user,amount,"Deposit Successfully!!","transactions/deposit_email.html")
        messages.success(self.request,
                         f'{"{:,.2f}".format(float(amount))}$ was deposited to your account successfully')
        return super().form_valid(form)
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawalFrom
    title = 'Withdrawal'
    
    def get_initial(self):
        initial = {'transaction_type':WITHDRAWAL}
        return initial
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance -= amount
        account.save(
            update_fields=['balance']
        )
        transaction_email_send(self.request.user,amount,"Withdraw Successfully!!","transactions/withdrawal_email.html")
        messages.success(
            self.request,
            f'Successfully withdrawn {"{:,.2f}".format(float(amount))}$ from your account'
        )
        return super().form_valid(form)

class TransferMoneyView(TransactionCreateMixin):
    form_class = TransferMoney
    title = 'Money Transfer'
    
    def get_initial(self):
        initial ={'transaction_type': TRANSFER_MONEY }
        return initial
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account_no = form.cleaned_data.get('account_no')
        account = self.request.user.account
        found_account = UserBankAccount.objects.get(account_no=account_no)
        account.balance -= amount
        found_account.balance += amount

        account.save(
            update_fields=['balance']
        )
        found_account.save(
            update_fields=['balance']
        )
        main_subject = "Transfer Money Successfully!!!"
        message = render_to_string('transactions/sender_email.html',{
            'user':account,
            'to_user':found_account,
            'amount':amount,
            'date_time':datetime.now()
            
        })
        to_email = account.user.email
        send_email = EmailMultiAlternatives(main_subject,'',to=[to_email])
        send_email.attach_alternative(message,"text/html")
        send_email.send()
        
        main_subject = f"You have recived Money to {account.user.first_name} {account.user.last_name}!!!"
        message = render_to_string('transactions/reciver_email.html',{
            'user':account,
            'to_user':found_account,
            'amount':amount,
            'date_time':datetime.now()
            
        })
        to_email = found_account.user.email
        send_email = EmailMultiAlternatives(main_subject,'',to=[to_email])
        send_email.attach_alternative(message,"text/html")
        send_email.send()
        # ---------------- Success Message ----------------
        messages.success(self.request,
                      f"${amount} successfully transferred"
                      f"from {account.account_no} to {account_no} 🎉"   
                         )
        return super().form_valid(form)

class LoanRequestView(TransactionCreateMixin):
    form_class = LoabRequestForm
    title = 'Request for Loan'
    
    def get_initial(self):
        initial = {'transaction_type': LOAN}
        return initial
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        current_loan_count =Transactions.objects.filter(account=self.request.user.account,transaction_type=3,loan_approve=True).count()
        if current_loan_count >=5:
            return HttpResponse("You have cross the loan limits")
            
        transaction_email_send(self.request.user,amount,"Apply For Loan Successfully!!","transactions/loan_email.html")    
        messages.success(
            self.request,
            f'Loan request for {"{:,.2f}".format(float(amount))}$ submitted successfully'
        )   
          

            
        return super().form_valid(form)
class TransactionReportView(LoginRequiredMixin,ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transactions
    balance = 0
    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account=self.request.user.account
        )
        start_date_str =self.request.GET.get('start_date')
        end_date_str =self.request.GET.get('end_date')
        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str,'%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str,'%Y-%m-%d').date()
            queryset = queryset.filter(timestamp__date__gte=start_date,timestamp__date__lte=end_date)
            self.balance = Transactions.objects.filter(timestamp__date__gte=start_date,timestamp__date__lte=end_date).aaggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance
        
        return queryset.distinct()
    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context.update({
            'account':self.request.user.account
        
        })
        return context
class PayLoanView(LoginRequiredMixin,View):
    def get(self,request,loan_id):
        loan = get_object_or_404(Transactions,id=loan_id)
        if loan.loan_approve:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transactions = user_account.balance
                user_account.save()
                loan.loan_approve =True
                loan.transaction_type = LOAN_PAID
                loan.save()
                return redirect('transactions:loan_list')
            else:
                messages.error(
            self.request,
            f'Loan amount is greater than available balance'
        )
        return redirect('loan_list')

class LoanListView(LoginRequiredMixin,ListView):
    model = Transactions
    template_name = 'transactions/loan_request.html'
    context_object_name = 'loans'
    
    def get_queryset(self):
        user_account =self.request.user.account
        queryset = Transactions.objects.filter(account=user_account,transaction_type=3)
        
        return queryset
                

transactions/templates/transactions/admin_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<h2>Congratulations!! Your Loan Request has been approved</h2>
<p>After loan approval your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us</p>
<p>Mamar Bank</p>

transactions/templates/transactions/deposit_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<p>Your Deposite request for ${{amount}} has been successfully completed. After deposite your total amount is {{user.account.balance}}</p>

<h4>Thanks for banking with us</h4>
<p>Babar Bank</p>

transactions/templates/transactions/loan_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<p>Your Loan request for ${{amount}} has been successfully sent to admin. Wait for admin approval.After getting admin approval you will get the loan and also get a confirmation mail</p>

<p>Thanks for banking with us</p>
<p>Mamar Bank</p>

transactions/templates/transactions/loan_request.html
{% extends 'base.html' %} 
{% block title %}{{ title }}{% endblock %} 
{% block content %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

transactions/templates/transactions/reciver_email.html
<div style="max-width:600px; margin:30px auto; padding:25px; border:1px solid #e0e0e0; border-radius:12px; font-family:Arial, sans-serif; background:#f9f9f9;">
  <h2 style="color:#2e7d32; text-align:center;">🎉 Congratulations You Have Received Money!</h2>
  
  <p style="font-size:16px; color:#333; line-height:1.5;">
    Dear <strong>{{to_user.user.first_name}} {{to_user.user.last_name}}</strong>,
  </p>

  <p style="font-size:16px; color:#333; line-height:1.5;">
    We are pleased to inform you that you have successfully received money from 
    <strong>{{user.user.first_name}} {{user.user.last_name}}</strong>.
  </p>

  <div style="background:#fff; border:1px solid #ddd; border-radius:10px; padding:15px; margin:20px 0;">
    <p style="margin:5px 0; font-size:15px;"><strong>Sender:</strong> {{user.first_name}} {{user.last_name}}</p>
    <p style="margin:5px 0; font-size:15px;"><strong>Amount Received:</strong> {{amount}}</p>
    <p style="margin:5px 0; font-size:15px;"><strong>Date & Time:</strong> {{date_time}}</p>
    
  </div>

  <p style="font-size:15px; color:#555; line-height:1.5;">
    The transferred amount is now available in your account.  
    You may review this transaction anytime in your account history.  
  </p>

  <p style="font-size:15px; color:#555; line-height:1.5;">
    Best Regards,<br>
    <strong>Babar Bank Team</strong>
  </p>
</div>

transactions/templates/transactions/sender_email.html
<div style="max-width:600px; margin:30px auto; padding:25px; border:1px solid #e0e0e0; border-radius:12px; font-family:Arial, sans-serif; background:#f9f9f9;">
  <h2 style="color:#2e7d32; text-align:center;">✅ Transaction Successful</h2>
  
  <p style="font-size:16px; color:#333; line-height:1.5;">
    Dear Customer {{user.user.first_name}} {{user.user.last_name}},
  </p>

  <p style="font-size:16px; color:#333; line-height:1.5;">
    We are pleased to inform you that your money has been successfully transferred to 
    <strong>{{to_user.user.first_name}} {{to_user.user.last_name}}</strong>.
  </p>

  <div style="background:#fff; border:1px solid #ddd; border-radius:10px; padding:15px; margin:20px 0;">
    <p style="margin:5px 0; font-size:15px;"><strong>Recipient:</strong> {{to_user.user.first_name}} {{to_user.user.last_name}}</p>
    <p style="margin:5px 0; font-size:15px;"><strong>Amount:</strong> {{amount}}</p>
    <p style="margin:5px 0; font-size:15px;"><strong>Date & Time:</strong> {{date_time}}</p>
    
  </div>

  <p style="font-size:15px; color:#555; line-height:1.5;">
    You can view the details of this transaction anytime in your account history.  
    Thank you for trusting our service.  
  </p>

  <p style="font-size:15px; color:#555; line-height:1.5;">
    Warm Regards,<br>
    <strong>Babar Bank Team</strong>
  </p>
</div>

transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %} {% block title %}{{ title }}{% endblock %} {% block content %}

<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Request For Loan' %}
<div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
        {% endif %}
        
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}
            {% if title == 'Money Transfer' %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="account_no">
                    To Account Number
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="account_no" id="account_no" type="number" required placeholder="To Account Number">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% else %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}

            {% endif %}
            
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                Submit
            </button>
            </div>
        </form>
    </div>
    
</div>
{% endblock %}

transactions/templates/transactions/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block title %} Transaction Report{% endblock %} {% block content %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

transactions/templates/transactions/withdrawal_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<p>Your Withdrawal request for ${{amount}} has been successfully completed. After deposite your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us</p>
<p>Mamar Bank</p>